name: "update-profile-stats"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: TTENSHII/github-profile-stats@v2
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          timezone: "Europe/Paris"
          output-file: "README.md"
          max-languages-to-show: 6
          min-language-percentage: 20
